### ISSUE TITLE
A problem with translation into Czech

### ISSUE THREAD

**Issue by Ravens62** [project-owner/Peppy#29] opened 2023-01-08 20:56 UTC
Hi, with the last two versions of the player I have a problem with communication. Immediately freezes the image on the screen, but the player normally plays, can control, work saver ...
Maybe more will say these 3 screeners

![Mix](https://user-images.githubusercontent.com/35656251/211218511-dcd130b2-038c-4673-80df-43bdb0297371.png)
![Mix1](https://user-images.githubusercontent.com/35656251/211218514-1a4c094f-cb38-4ea7-8582-e2e3b8fdd616.png)
![Mix2](https://user-images.githubusercontent.com/35656251/211218520-258e47c0-65f9-4621-b2d2-c187c1bc6c8c.png)

The first one is visibly bad
The other one occurs after switching the radio station
The third is a short statement from the logo
The English language doesn't do it to me.

**Comment by project-owner** [comment] 2023-01-09 03:36
Hi,

What's wrong with those images?
Please let me know how I could reproduce the issue? What is the sequence of steps which leads to the issue?
Do you use Pi3 or 4? What kind of configuration changes you made?

Thank you!

**Comment by Ravens62** [comment] 2023-01-09 14:36
The first picture shows a different song and another picture of the album.
There is nothing in the second picture, just the station.
This happens for me randomly, the radio plays, the screen is running a saver.
Then I want to see who plays it and it is in that state.
Sometime in an hour, sometimes before ...
I have to make a reboot out of my computer.

My combination is:
RPI4, Waveshare 4.3 "DSI LCD display, IPS, 800 × 480, I2C, MIPI DSI,
HIFIBERRY DAC-PLUS.

**Comment by project-owner** [comment] 2023-01-09 16:51
As far as I understand the problem is that the player shows either wrong image/song title or shows station name/logo instead of album cover/song name.
Does it happen only with that particular station or any station? Which screensaver do you use? does it help if you switch to another station and then back? Do you have a backlight control enabled?
https://github.com/project-owner/Peppy/blob/0f4870f211cde0f9aa5d7c1e5bf3aaa00679ebb3/config.txt#L179

I'll try to use the same station and see if I can reproduce the issue.

Best regards

**Comment by project-owner** [comment] 2023-01-09 20:04
I think I found the root cause of the issue related to album art images. I'll let you know the fix after testing it.

Regarding that ERROR issue - which genre did you use when that happens? The URL should include a genre name (e.g. Rock) instead of 'undefined':
[2023-01-09 19:04:53,557] {web.py:2243} INFO - 200 GET /playlists?language=Czech&genre=undefined&folder=%C5%BD%C3%A1nry (192.168.0.10) 5.85ms

Thank you!

**Comment by Ravens62** [comment] 2023-01-09 20:42
Well now I'm listening to Rock, Radio Čas Rock.
But the nonsense that appeared there was only a consequence of loading the protocol file. Just like now again ...

[2023-01-09 21:14:31,611] {web.py:2243} INFO - 200 GET /playlists?language=Czech&genre=Retro&folder=%C5%BD%C3%A1nry (192.168.0.10) 3.52ms
[2023-01-09 21:14:31,619] {web.py:2243} INFO - 200 GET /log (192.168.0.10) 3.91ms
[2023-01-09 21:14:31,640] {web.py:2243} INFO - 200 HEAD /config/icon/Czech/radio-stations/%C5%BD%C3%A1nry/Retro/Evropa%202%20Flashback.png (192.168.0.10) 7.93m

**Comment by project-owner** [comment] 2023-01-09 20:51
INFO messages are OK. I'm wondering when you get the ERROR messages? Did you open playlists in Web UI?

Thank you!

**Comment by Ravens62** [comment] 2023-01-09 21:51
On the web interface I open the settings/System/Log File or. I will refresh

**Comment by project-owner** [comment] 2023-01-09 22:04
Are those ERROR messages reproducible? If so, is it possible to list all steps which lead to the ERROR messages? Thanks!

**Comment by Ravens62** [comment] 2023-01-09 22:19
At the moment no erorr in the log :-),
I'll see again tomorrow, now I'm going to sleep.
So far thanks for help.

**Comment by project-owner** [comment] 2023-01-09 22:50
OK, let's fix the issue with album art and then switch to ERROR messages.
You can find the explanation of the album art issue and how to resolve it here:
https://github.com/project-owner/PeppyPlayers.doc/wiki/Known-Issues#signac-edition
Please let me know if it helps. Thanks!

**Comment by Ravens62** [comment] 2023-01-10 15:24
At the moment no erorr in the log :-),
I'll see again tomorrow, now I'm going to sleep.
So far thanks for help.

**Comment by Ravens62** [comment] 2023-01-10 15:24
Hi,
So until now it works without mistakes :-)
So I would say it's ok

Thanks for solving

**Comment by project-owner** [comment] 2023-01-10 16:54
Great, thank you for reporting the issue. The fix will improve the radio functionality.
I'll close this issue. If you will face any other issues please open another one.

Best regards

**Closed by project-owner** 2023-01-10 16:54 UTC
