### ISSUE TITLE
Freez GUI

### ISSUE THREAD

**Issue by Ravens62** [project-owner/Peppy#14] opened 2021-07-06 09:15 UTC
Hi,
I use the Monet edition, and GUI is freezing when the weather is switched. It will only happen in this saver or when the weather is selected from the popup button on the player screen.
Here's a piece of log:
[2021-07-06 11: 04: 29,195] {Discogsutil.py:109} Debug - https://img.discogs.com/6RANYTQC4M-2DR4IZNHIVJ8NEW8=/FIT-IN/600X578/FILTERS:STRIP_ICC (): Format () JPEG: Mode_RGB (): Quality (90) /Discogs-images/r-1731289-1268889622.jpeg.jpg
[2021-07-06 11: 07: 54,124] {connectionpool.py:815} debug - starting new https connection (1): api.openweathermap.org:443
[07.06.2021 11: 07: 55.319] {} connectionpool.py:393 Debug - https://api.openweathermap.org:443 "GET /data/2.5/onecall?APPID=02d9ad369057d92987a9585cc08e7f&lon=18.2268315177587&lat=49.5322247923045&exclude = minutes% 2chourly% 2calerts & units = Metric HTTP / 1.1 "200 4283

**Comment by project-owner** [comment] 2021-07-06 14:47
Hi, does it freeze forever or just for some period of time?

Did you copy/paste the log from the player output without manually changing it? It should be 'minutely' instead of 'minutes'. Also it should be without spaces. 

You can use the code block <> from the menu to insert the log. Which language do you use?
I've tried to use your coordinates in player and worked fine for me. You can try that URL in the browser. For example I edited your URL - just removed spaces and changed 'minutes' to 'minutely' and tried in browser. It worked fine:
```
https://api.openweathermap.org:443/data/2.5/onecall?APPID=02d99bad369057d92987a9585cc08e7f&lon=18.2268315177587&lat=49.5322247923045&exclude=minutely%2chourly%2calerts&units=metric
```

**Comment by Ravens62** [comment] 2021-07-06 15:54
Hi,
Frozen forever, I use translation into Czech, which I did myself could listen to Czech stations and not combine the English language and Czech radio. I did not modify the log, just whenever the weather query will be asked, so the entire player freezes. But I found only graphically, thus not to control but music plays on. So I wondered, I edited the Bluetooth service, just not remember if it had no longer before:
editing this file

/etc/systemd/system/dbus-org.bluez.service

and changing this line

ExecStart=/usr/lib/bluetooth/bluetoothd

to this

ExecStart=/usr/lib/bluetooth/bluetoothd --compat

and then restarting bluetooth like this

sudo systemctl daemon-reload
sudo systemctl restart bluetooth

and you'll also have to change permissions on /var/run/sdp

sudo chmod 777 /var/run/sdp

Indeed, before this repair, it freeze the player when you try to connect to the Internet. I found that Bluetooth does not work and when you try to fix it, the page with connection normally began

**Comment by project-owner** [comment] 2021-07-06 16:18
If you would like I could add Czech language to the player so that you would not need to add it every release. Also other users could benefit from it. Just contact me (peppy.playerATgmail.com) if you will decide to share your translations and radio stations.

Does the Weather work with English language? Maybe there is some missing translation (?)

**Comment by Ravens62** [comment] 2021-07-06 16:40
Hi,
So in English, the weather works, there is no freezing ...

Here's a piece of log:
[2021-07-06 18:32:44,304] {connectionpool.py:393} DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/onecall?APPID=02d99bad369057d92987a9585cc08e7f&lang=en&lon=18.2268315177587&lat=49.5322247923045&exclude=minutely%2Chourly%2Calerts&units=metric HTTP/1.1" 200 4280

**Comment by project-owner** [comment] 2021-07-06 16:55
You need to add Czech to this function:
https://github.com/project-owner/Peppy/blob/c934ac87da3ae3f6b42079654692a50538c9faf0/util/util.py#L220
like this:
```
        elif language == "Czech":
            code = "cz"
```
Please let me know if it works after that.

**Comment by Ravens62** [comment] 2021-07-06 19:23
Hi,
So it didn't help. It seems to change the question but still freezes it.

[2021-07-06 21:17:18,676] {connectionpool.py:815} DEBUG - Starting new HTTPS connection (1): api.discogs.com:443
[2021-07-06 21:17:20,050] {connectionpool.py:393} DEBUG - https://api.discogs.com:443 "GET /database/search?q=BLACK%20SABBATH%20-%20Changes&page=1&per_page=50&token=RtZmsbvvoXVQxBwXtYDkbNIOXWkeGILJeyriGmDL HTTP/1.1" 200 None
[2021-07-06 21:18:26,795] {connectionpool.py:815} DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
[2021-07-06 21:18:27,385] {connectionpool.py:393} DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/onecall?APPID=02d99bad369057d92987a9585cc08e7f&lang=cz&lon=18.2268315177587&lat=49.5322247923045&exclude=minutely%2Chourly%2Calerts&units=metric HTTP/1.1" 200 4294

**Comment by project-owner** [comment] 2021-07-06 19:55
OK, now the URL in the log is correct. Can you send me over e-mail (peppy.playerATgmail.com) the following files:
/home/pi/Peppy/languages/languages.txt
/home/pi/Peppy/languages/Czech/labels.properties
I'll try to use them on my side to see if the issue is there.
Thanks!

**Comment by project-owner** [comment] 2021-07-06 21:13
Thank you for the files! It looks like there are several translations missing in the file labels.properties:
humidity = Humidity
mph = km/h
sunrise = Sunrise
sunset = Sunset
weekday.0 = Mon
weekday.1 = Tue
weekday.2 = Wed
weekday.3 = Thu
weekday.4 = Fri
weekday.5 = Sat
weekday.6 = Sun
wind = Wind
I sent you the file with missing labels in English. You can translate those labels and I hope it will start working after that.

**Comment by Ravens62** [comment] 2021-07-07 14:20
Hi,
It looks functional yet. I probably used an older translation without thorough control.

**Comment by project-owner** [comment] 2021-07-07 15:36
Cool! Closing the issue.

**Closed by project-owner** 2021-07-07 15:36 UTC
