### ISSUE TITLE
Playback from a Collection 2

### ISSUE THREAD

**Issue by Ravens62** [project-owner/Peppy#33] opened 2023-03-17 12:08 UTC
Hi,
I have to bother you again. I can play whole albums, but if I try to play just one song from an album the player screen freezes. I don't know if there is some connection with the data loading, because the file info is blank but the data in the db is there.
After selecting a song it shows me which album it is in, but then it freezes and it only goes to reboot from the WebUI.

The tags are written in the format 
ID3v2.3 UTF 16 are not visible in the info
FLAC ones are visible
but both cause the screen to freeze, the music continues to play the one that was previously selected by selecting that song.
![Info 2](https://user-images.githubusercontent.com/35656251/225900138-386b43f7-8994-41dd-99ac-33a2743cee75.png)

![Info](https://user-images.githubusercontent.com/35656251/225895429-c23aac0a-afb9-4b74-a30d-f89731184f6a.png)
![Info db](https://user-images.githubusercontent.com/35656251/225895449-22ee227d-6311-4667-af9c-9be3deda8ef5.png)

**Comment by project-owner** [comment] 2023-03-17 21:05
Hi, I need more info to reproduce the issue on my side. Can you play those files without collection? Does it happen with any file or just particular files? What do you select on the Collection screen? Title or File?
Thanks!

**Comment by Ravens62** [comment] 2023-03-17 22:02
Hi,
I can play individual files through Audio files in menu.
![Audio](https://user-images.githubusercontent.com/35656251/226060820-79e4c838-ee48-47cf-be61-e20f1a83f8ac.png)

This happens with any file selected via Title.
![Titul](https://user-images.githubusercontent.com/35656251/226060518-a5197a86-2db0-46ee-af02-d64b106d3cdc.png)

In the screenshot, the screen is already frozen.
I have to reboot via WebUI.
And there is nothing in the log, just Debug, no error.

I hope I'm writing clearly, I'm trying another translator instead of google :-)

**Comment by project-owner** [comment] 2023-03-17 22:12
OK, it looks like the issue was caused by my previous change in collection code. It should be fixed now. Get the fix this way:
```
cd Peppy
git fetch
git checkout origin/master -- ui/screen/topicdetail.py
```
Thank you!

**Comment by Ravens62** [comment] 2023-03-18 21:30
Hi,
Yeah, it works. It plays the selected song and then continues playing the album from that song.
Nice work.

**Closed** 2023-03-18 22:02 UTC
