### ISSUE TITLE
Upgrading: version support for Raspberry OS/Debian releases?

### ISSUE THREAD

**Issue by DrTron** [project-owner/Peppy#53] opened 2024-04-04 15:22 UTC
All,

I'm thinking about upgrading my player currently running Buster/Marc.
That was mainly because Marc didn't run on Bullseye.

Does the current Malevich edition run on bookworm, the current Debian stable?
Or should I not mess with it as it's running well as it is?

Thanks!

**Comment by project-owner** [comment] 2024-04-05 04:50
Hi,

Ye, the current Malevich Edition runs on Bookworm:
https://forums.raspberrypi.com/viewtopic.php?t=139983&start=425#p2199529
There are some limitations caused by moving to the Bookworm OS. For example, there are no disk images for SPI displays and no sliding actions. If that's OK for you then you can use this edition.

Best regards

**Comment by DrTron** [comment] 2024-04-06 19:10
Thanks, I'll see if I can get both the OS and Peppy upgraded and working again...

**Closed** 2024-07-08 21:36 UTC
Labels: question
